// Generated by CoffeeScript 1.9.0

/*
 Fluidity
 Copyright (c) 2012 Kris Hedges <kris@inkspeck.com>, http://Inkspeck.com
 MIT Licensed
 */
var exports, nodes, plugin, stylus, utils;

stylus = require('stylus');

nodes = stylus.nodes;

utils = stylus.utils;

exports.version = '0.1.6';

exports.path = __dirname;

plugin = function() {
  return function(style) {
    return style.include(__dirname);
  };
};

exports = module.exports = plugin;
